# Generated by Django 5.2.1 on 2025-05-22 06:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audioframe',
            name='client_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='audioframe',
            name='conversation_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
