# Generated by Django 5.2.1 on 2025-05-22 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_audioframe_client_timestamp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transcription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fast_transcription', models.TextField(blank=True, null=True)),
                ('slow_transcription', models.TextField(blank=True, null=True)),
                ('audio_frame', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transcription', to='app.audioframe')),
            ],
        ),
    ]
