# Generated by Django 5.2.1 on 2025-05-29 08:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_transcription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audioframe',
            name='conversation_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='transcription',
            name='fast_transcription',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transcription',
            name='slow_transcription',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ConversationAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_id', models.UUIDField(db_index=True, editable=False)),
                ('analysis_type', models.CharField(max_length=100)),
                ('analysis', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audio_frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.audioframe')),
            ],
        ),
    ]
