# Generated by Django 5.2.1 on 2025-05-30 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_audioframe_conversation_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcription',
            name='fast_transcription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transcription',
            name='slow_transcription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
