# Generated by Django 5.2.1 on 2025-05-30 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_transcription_fast_transcription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationanalysis',
            name='analysis',
            field=models.JSONField(null=True),
        ),
    ]
